add: データベース構築 #7
ap-7th-team2/team_development_1 pull request #8
Opened 2024-11-25 15:10 UTC by Megumin32

# Pull Request

データベース構築

## 関連Issue
close #7 

## PRタイプ
* 📖ドキュメント整備
* 💻環境構築

## 変更内容
- データベース構築用SQLスクリプトを作成
- データベース接続テストRubyスクリプトを作成
- ドキュメントファイルの作成

## 影響範囲
特になし

## 動作確認
`documents/database.md`に手順が書いてあるので，手順に従って動作確認をお願いします．

## チェックリスト
- [] テーブルが作成されているか
- [] Rubyによりテーブルを取得できるか

## レビュワーへの注意点・相談内容・懸念点
特になし

2024-11-25 15:59 UTC, daisuke721 requested changes
データベースの実装ありがとうございます👍
動作確認はdatabase.mdの仕様書に沿って実行しましたが問題なく実行できました！

ちょっと気になった細かいところなどコメントしておりますので再度修正のほどよろしくお願いします🙇‍♂️

2024-11-25 15:59 UTC, daisuke721 commented on routes/snippet.rb
> +DB_NAME = ENV['DATABASE_NAME']
MySQLの環境変数を新たにroutes.rbで定義してますのでserver.rbの環境変数は削除しても大丈夫です！

2024-11-25 15:59 UTC, daisuke721 commented on documents/database.md
> +docker exec -it team_development_1-db-1 mysql -u root -p
一度、コンテナ内に入っていますのでmysql -u root -pのみでログインできました！

2024-11-25 15:59 UTC, daisuke721 commented on db/init.sql
> +    copy_count INT,
テーブル定義書には初期値が設定されているので設定お願いします🙏

2024-11-26 12:39 UTC, Megumin32 commented
修正しました！確認お願いします．

2024-11-26 15:36 UTC, daisuke721 commented
修正ありがとうございます！
環境変数の件はsnippet.rbで新たに川上さんが定義してくださったのでserver.rbの環境変数は不要という意味でした！
なのでsnippet.rbの環境変数は残していただいて問題ないです！

snippet.rb
```ruby
# 必要なので削除不要です
DB_HOST = ENV['DATABASE_HOST']
DB_USER = ENV['DATABASE_USER']
DB_PASSWORD = ENV['DATABASE_PASSWORD']
DB_NAME = ENV['DATABASE_NAME']
```

server.rb
```ruby
# 不要なので削除してください
DB_HOST = ENV['DATABASE_HOST']
DB_USER = ENV['DATABASE_USER']
DB_PASSWORD = ENV['DATABASE_PASSWORD']
DB_NAME = ENV['DATABASE_NAME']
```

2024-11-26 22:44 UTC, Megumin32 commented
snippet.rb直しました．

2024-11-27 07:07 UTC, daisuke721 commented
LGTMです👍修正ありがとうございました！

2024-11-27 07:07 UTC, daisuke721 approved these changes

2024-11-27 07:07 UTC, merged